# ==============================================================================
# Fonts Configuration
# ==============================================================================

FONT_NAME="JetBrainsMono Nerd Font"

FONT_ARCHIVE_NAME="JetBrainsMono"
