# ==============================================================================
# GitHub CLI Configuration
# ==============================================================================

GH_GIT_PROTOCOL="ssh"
