"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nodejs\
$bun\
$python\
$package\
$docker_context\
$cmd_duration\
$time\
$line_break\
$character"""

[os]
disabled = false
format = "[$symbol]($style) "
style = "bold blue"

[os.symbols]
Ubuntu = "🐧"

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold yellow"
style_root = "bold red"

[hostname]
ssh_only = false
format = "[@$hostname]($style) "
style = "bold green"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[cmd_duration]
min_time = 500

[time]
disabled = false
format = "at [$time]($style)"
style = "bold dimmed white"
time_format = "%H:%M:%S"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
